#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "docs"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco.cx"

[[routes]]
pattern = "docs.decocms.com"
custom_domain = true

[assets]
directory = "./dist/client"
binding = "ASSETS"

[deco]
workspace = "deco.cx"
bindings = []
enable_workflows = true
local = false